# config.yaml

scoring_system: default
current_year: 2024
top_n: 100
years_order: [2017, 2018, 2019, 2021, 2022, 2023, 2024]
input_paths:
  - "data/shortboard/shortboard_men_*.csv"
  # - "data/longboard/longboard_men_*.csv"
  # - "data/shortboard/shortboard_women_*.csv"
  # - "data/longboard/longboard_women_*.csv"

output:
  filename: ranking/shortboard_men.csv
  # filename: ranking/longboard_men.csv
  # filename: ranking/shortboard_women.csv
  # filename: ranking/longboard_women.csv
  columns: [Rank, Name, Birthday, Region, Category, Best Place, YearScores, Total Points]

sorting:
  enabled: true

filtering:
  enabled: false
  max_place: 16  # Включать только тех, кто хотя бы раз занял место не хуже указанного

scoring:
  default:
    1: 1000
    2: 900
    3: 800
    4: 700
    5-8: 500
    9-16: 300
    17-32: 100
    DNS: 0

  wsl:
    1: 10000
    2: 7800
    3-4: 6085
    5-8: 4745
    9-16: 3320
    17-32: 1330
    DNS: 0

  custom_wsl:
    1: 10000
    2: 8000
    3: 6400
    4: 5120
    5-8: 4096
    9-16: 3072
    17-32: 1024
    DNS: 0

bonuses:
  decay:
    enabled: true
    factor: 0.9

  rank:
    enabled: false
    values:
      МС: 80
      КМС: 50
      "1 разряд": 30
      "2 разряд": 20
      "3 разряд": 10
      "": 0

  participation:
    enabled: false
    points: 50

wildcard:
  top_n: 16               # Максимальный ранг для отбора
  min_participations: 2   # Минимальное количество участий
  last_years_period: 3    # За последние N лет
  min_best_place: 3       # Лучший результат за карьеру

  # ranking_file: ranking/shortboard_men.csv
  # output_file: wildcard/shortboard_men.csv

  # ranking_file: ranking/shortboard_women.csv
  # output_file: wildcard/shortboard_women.csv

  # ranking_file: ranking/longboard_women.csv
  # output_file: wildcard/longboard_women.csv

  ranking_file: ranking/longboard_men.csv
  output_file: wildcard/longboard_men.csv

trends:
  # input_ranking_file: ranking/shortboard_men.csv
  # output_general_file: stats/trends/general_shortboard_men_stats.csv
  # output_detailed_file: stats/trends/detailed_shortboard_men_stats.csv

  # input_ranking_file: ranking/longboard_men.csv
  # output_general_file: stats/trends/general_longboard_men_stats.csv
  # output_detailed_file: stats/trends/detailed_longboard_men_stats.csv

  # input_ranking_file: ranking/longboard_women.csv
  # output_general_file: stats/trends/general_longboard_women_stats.csv
  # output_detailed_file: stats/trends/detailed_longboard_women_stats.csv

  input_ranking_file: ranking/shortboard_women.csv
  output_general_file: stats/trends/general_shortboard_women_stats.csv
  output_detailed_file: stats/trends/detailed_shortboard_women_stats.csv
